# Generated by Django 3.1 on 2020-08-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.TextField(default='Ganatunes: Bollywood,songs,movies', max_length=250),
        ),
    ]
